version: '3.7'

services:

  fulfilment-processor:
    image: courselabs/fulfilment-processor
    build:
      context: ./fulfilment-processor

  fulfilment-web:
    image: courselabs/fulfilment-web
    build:
      context: ./fulfilment-frontend
      dockerfile: fulfilment-web/Dockerfile

  fulfilment-api:
    image: courselabs/fulfilment-api
    build:
      context: ./fulfilment-api

  fulfilment-authz:
    image: courselabs/fulfilment-authz
    build:
      context: ./fulfilment-frontend
      dockerfile: fulfilment-authz/Dockerfile